sudo: required
services:
  - docker

env:
  - NPM_VERSION=8-jessie
    NPM_VERSION=6-jessie

script:
  - docker login -u="$DOCKER_USERNAME" -P="$DOCKER_PASSWORD"
  - docker build -t node:$NODE_VERSION --build-arg NODE_IMAGE="node:{$NODE_VERSION}" .
  - docker images
  - docker tag node:$NODE_VERSION $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD)
  - docker push $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD)

stages:
  - test
  - npm-targets

jobs:
  include:
    - stage: npm-targets
      name: "Test 8-jessie "
      install: skip
      script: -docker run --rm $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD) npm run $NMP_TARGET
      env:
        - NODE_VERSION=8-jessie
        - NPM_TARGET=test
    - stage: npm-targets
      name: "Test 8-jessie "
      install: skip
      script: -docker run --rm $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD) npm run $NMP_TARGET
      env:
        - NODE_VERSION=8-jessie
        - NPM_TARGET=lint
    - stage: npm-targets
      name: "Test 8-jessie "
      install: skip
      script: -docker run --rm $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD) npm run $NMP_TARGET
      env:
        - NODE_VERSION=8-jessie
        - NPM_TARGET=coverage

        - stage: npm-targets
          name: "Test 6-jessie "
          install: skip
          script: -docker run --rm $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD) npm run $NMP_TARGET
          env:
            - NODE_VERSION=8-jessie
            - NPM_TARGET=test
        - stage: npm-targets
          name: "Test 6-jessie "
          install: skip
          script: -docker run --rm $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD) npm run $NMP_TARGET
          env:
            - NODE_VERSION=8-jessie
            - NPM_TARGET=lint
        - stage: npm-targets
          name: "Test 6-jessie "
          install: skip
          script: -docker run --rm $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD) npm run $NMP_TARGET
          if: branch=master
          env:
            - NODE_VERSION=8-jessie
            - NPM_TARGET=coverage
